version: '3.7'

services:
    app:

        build: 
            context: .
            dockerfile: Dockerfile
        command: streamlit run app/app.py --server.port 8501
        volumes:
            - /app
        ports:
            - 8501:8501
        image: mystreamlitapp:latest



  
